services:
  postgres:
    image: postgres:16-bookworm
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pbaabp
      POSTGRES_PASSWORD: pbaabp
      POSTGRES_DB: pbaabp
      POSTGRES_HOST_AUTH_METHOD: trust  # never do this in production!
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pbaabp", "-d", "pbaabp"]
      interval: 1s

  redis:
    image: redis:7-bookworm
    ports:
      - "6379:6379"
    healthcheck:
     test: ["CMD", "redis-cli","ping"]
     interval: 1s

  web:
    build: .
    image: pbaabp-web:docker-compose
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DEBUG: true
      DATABASE_URL: postgresql://pbaabp:pbaabp@postgres:5432/pbaabp
      DJANGO_ALLOWED_HOSTS: "localhost"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:8000"
      DJANGO_EMAIL_SUBJECT_PREFIX: "[Philly Bike Action!]"
      DJANGO_EMAIL_HOST: "maildev"
      DJANGO_EMAIL_PORT: 1025
      DJANGO_EMAIL_USE_TLS: "False"
      DJANGO_DEFAULT_FROM_EMAIL: "pba@example.com"
      STRIPE_API_HOST: "http://stripe:12111"
      STRIPE_TEST_SECRET_KEY: "sk_test_4eC39HqLyjWDarjtT1zdp7dc"
      STRIPE_TEST_PUBLIC_KEY: "pk_test_TYooMQauvdEDq54NiTphI7jx"
      DJANGO_READ_DOT_ENV_FILE: "True"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  worker:
    image: pbaabp-web:docker-compose
    command: hupper -m celery -A pbaabp worker --beat -l DEBUG
    volumes:
      - .:/code
    environment:
      DATABASE_URL: postgresql://pbaabp:pbaabp@postgres:5432/pbaabp
      DJANGO_ALLOWED_HOSTS: "localhost"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:8000"
      DJANGO_EMAIL_SUBJECT_PREFIX: "[Philly Bike Action!]"
      DJANGO_EMAIL_HOST: "maildev"
      DJANGO_EMAIL_PORT: 1025
      DJANGO_EMAIL_USE_TLS: "False"
      DJANGO_DEFAULT_FROM_EMAIL: "pba@example.com"
      STRIPE_API_HOST: "http://stripe:12111"
      STRIPE_TEST_SECRET_KEY: "sk_test_4eC39HqLyjWDarjtT1zdp7dc"
      STRIPE_TEST_PUBLIC_KEY: "pk_test_TYooMQauvdEDq54NiTphI7jx"
      DJANGO_READ_DOT_ENV_FILE: "True"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  discord:
    image: pbaabp-web:docker-compose
    command: python manage.py run_dev_discord
    stop_signal: SIGINT
    volumes:
      - .:/code
    environment:
      DATABASE_URL: postgresql://pbaabp:pbaabp@postgres:5432/pbaabp
      DJANGO_READ_DOT_ENV_FILE: "True"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  stripe:
    image: stripe/stripe-mock:v0.186.0

  maildev:
    image: maildev/maildev:2.0.5
    ports:
      - "1080:1080"
      - "1025:1025"
